### ISSUE TITLE
Default project title and description are empty

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#116]
<img width="525" alt="screen shot 2018-02-07 at 12 04 45 am" src="https://user-images.githubusercontent.com/203725/35905069-892c6352-0b9a-11e8-91f6-6f978bb96f87.png">

When using the sample Unity Asset Package, and if you don't specify a title, the `%UNITY_CUSTOM_NAME%` and `%UNITY_CUSTOM_DESCRIPTION%` values (defined in the `index.html` template) are blank.

@delapuente: I asked about this in some PR a few days ago, but I think I missed/forgot your response. What's the expected behaviour here for devs?

Shouldn't we just use `%UNITY_WEB_NAME%` (per [Unity's docs](https://docs.unity3d.com/Manual/webgl-templates.html)) like it was before?

**Comment by cvan** [comment]
I notice when I build the project from scratch, and export the build to `Build/`, this gets changed for me:

```diff
index 68727bf..9d7cde6 100644
--- a/Build/Build/Build.json
+++ b/Build/Build/Build.json
@@ -1,13 +1,11 @@
 {
-"companyName": "DefaultCompany",
-"productName": "Unity-WebVR-Export",
```

Am I doing something weird on my end?

**Comment by delapuente** [comment]
That's the name of the player, not the game. Per Unity documentation:
```
UNITY_WEB_NAME: Name of the player.
```
We can provide default names if that is even possible.

**Comment by cvan** [comment]
@delapuente thanks for clarifying! :smile:

that was/still is confusing to me. will it/is it confusing to Unity game devs? worth documenting here in this project's docs.

**Comment by cvan** [comment]
FYI: this affects the version published on https://mozilla.github.io/unity-webvr-export/Build/

**Comment by cvan** [comment]
This seems fixed. Are [these](https://github.com/mozilla/unity-webvr-export/blob/f0e2e74/ProjectSettings/ProjectSettings.asset#L14-L15) the correct defaults?

![image](https://user-images.githubusercontent.com/203725/39078736-95b093e4-44c2-11e8-8cfd-d2d9f87f1e25.png)
