### ISSUE TITLE
add a keyboard shortcut for entering/exiting VR mode

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#124]
I'd recommend a keypress of the `v` key (without any alt/shift/control/meta keys held).

**Comment by delapuente** [comment]
Let's make it configurable in Unity but I'll provide `v` as the default.

**Comment by delapuente** [comment]
Currently, you need to use [JavaScript key names](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values), not Unity labels. I.e. if you want the spacebar to be the key for quick toggle, use a blank space ` `.
