### ISSUE TITLE
Unexpected behavior when dragging in 2D Fallback

### ISSUE THREAD

**Issue by Legorobotdude** [mozilla/unity-webvr-export#148]
When I drag in Firefox, somethings I get the drag symbol and the scene does not pan, but begins panning when I release the mouse. See these links for possibly related issues and fixes: https://forum.unity.com/threads/web-gl-mouse-input-glitch-on-chrome.468362/ https://www.reddit.com/r/Unity3D/comments/7xrc5k/webgl_input_bug_solution_on_chrome/

**Comment by caseyyee** [comment]
@Legorobotdude are you still experiencing this?   Since the refactor, it should be fixed now.
Try at: https://mozilla.github.io/unity-webvr-export/

**Comment by cvan** [comment]
@Legorobotdude thanks for filing and continuing to experiment with the project. could you try it now from https://mozilla.github.io/unity-webvr-export/?

**Comment by Legorobotdude** [comment]
Looks like it is fixed now, closing the issue.

**Comment by cvan** [comment]
thanks for following up! appreciate your contributions and comments, @Legorobotdude! :+1:
