### ISSUE TITLE
Document how to test VR in Unity editor

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#155]
To experiment with VR prior to exporting, you must enable VR in the player settings for a native platform. We should put this in the documentation somewhere.

**Comment by AjaySharvesh3** [comment]
To test VR in Unity Editor we have to enable the VR in Player Settings. To check where the player setting is File -> Built Settings -> Bottom left corner Player setting will be shown, click on that and right side you will see XR setting. In XR settings enable Virtual Reality Support. And then test, it should work
![capture](https://user-images.githubusercontent.com/27482105/37072167-023b24ac-21e6-11e8-8cdb-09706fc1f64d.JPG)
.

**Comment by cvan** [comment]
FYI: @caseyyee in his last PR changed this to default to enabled now: https://github.com/mozilla/unity-webvr-export/commit/f0e2e741351fc97995ec72c0c5e3329ae1b02099#diff-988fde71e6a4c917d4d31be70b435aa1

**Comment by caseyyee** [comment]
@cvan This still needs to be documented since it won't be checked on if you are importing the asset as a package.  It only works if you open up the project from this repo.

**Comment by cvan** [comment]
handled in PR #297. feel free to take a look for review. thanks! 👍

**Comment by caseyyee** [comment]
@Banyango like this idea!

**Comment by cvan** [comment]
merged in PR #297
