### ISSUE TITLE
collect default, opt-out basic performance timing data in Google Analytics (as custom GA events)

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#170]
Google Analytics are to be added in issue #169. This issue is for adding performance metrics around page loading, emscripten module loading, and canvas + WebGL performance.

Just like as with issue #169, collecting and submitting this information is opt-out-able and we're including it so we can properly instrument performance issues and improve the stability of this project.

Check out the numerous [JavaScript APIs available in the browser](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API#Specifications) with which to instrument various performance data.

<hr>

Parent issue: #165
Related issues:
- #169 for adding default snippet for Mozilla's Google Analytics,
- #167 for creating Help modal,
- #164 for documenting/messaging

**Comment by cvan** [comment]
found this very relevant list of projects: https://wiki.mozilla.org/CloudServices/DataPipeline

**Comment by delapuente** [comment]
We should assess the feasibility of measuring emscripten module loading (although I think you mean wasm modules) and define what it is to measure canvas + WebGL performance in separated bugs.

**Comment by cvan** [comment]
basic performance timings handled in PR #189 by @delapuente!

we will file additional specific metrics we want to profile as we discover from users/developers what we need.
