### ISSUE TITLE
missing terrain on fresh Unity build on `master`

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#177]
Reproducible on `master` on both macOS and Windows with Unity `2017.3.1f1` Personal Edition.

![image](https://user-images.githubusercontent.com/203725/36778793-a814497c-1c22-11e8-9459-9c6ca253c1fa.png)

**Comment by delapuente** [comment]
In Unity is the same, the camera is at 0, 0, 0. So, in the preview, you see no ground:
![ground-level](https://user-images.githubusercontent.com/757942/36835570-f79418fa-1d36-11e8-8259-05491f5b3a45.png)

But as soon as you click on `Play` it appears:
![in-game-camera-position](https://user-images.githubusercontent.com/757942/36835888-f145c434-1d37-11e8-8a13-c9a740940ace.png)

**Comment by caseyyee** [comment]
Hmm.  that seems to be different than what I saw.  Maybe we're fine then.
We can start a separate issue for applying a default stand height when in-editor.

**Comment by delapuente** [comment]
Feel free to open the bug you suggest. Closing this.
