### ISSUE TITLE
desktop instructions show twice on startup

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#179]
Need to click continue twice.  Once on Unity ready, and another time when Unityload event fires.

**Comment by cvan** [comment]
@caseyyee On which browser and operating system? I haven't seen this before.

**Comment by caseyyee** [comment]
Desktop FF and Chrome.

I noticed when I was fixing 2D fallback, that errors were being thrown twice.  we're calling `getVRDisplay` function on both `Unityload` event and the `ready` message were getting back from Unity.  Checkout the PR I ref'd.
