### ISSUE TITLE
Reset camera position after enter/exit VR

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#184]
Before entering and after exiting VR, we should reset camera position/rotation so that it doesn't freeze in the last headset position.  Makes it appear broken.

**Comment by cvan** [comment]
@delapuente: this is covered by PR #213, right? (also, see the helpful issue filed by @LordSkittles in #218.)

**Comment by caseyyee** [comment]
Fixed with https://github.com/mozilla/unity-webvr-export/commit/9916e8c4bd1a3af381a96b9387aeb82a4a00fd0e
