### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#19]
rather than just loading project.

**Comment by cvan** [comment]
Relevant: https://github.com/caseyyee/unity-webvr-export/issues/62#issuecomment-360444756

**Comment by caseyyee** [comment]
https://github.com/mozilla/unity-webvr-export/pull/118

**Comment by caseyyee** [comment]
Addressed in Getting Started, Project setup doc: https://github.com/mozilla/unity-webvr-export/blob/master/docs/project-setup.md

and FAQ https://github.com/mozilla/unity-webvr-export/blob/master/docs/troubleshooting-faq.md
