### ISSUE TITLE
Add credit @chrmi  Chris Miller

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#204]
https://github.com/chrmi/unity-webvr

**Comment by delapuente** [comment]
What kind of credit? Let's move this forward, it seems trivial and we should recognize the job of everybody we have used its work or take inspiration from. @caseyyee ?

**Comment by caseyyee** [comment]
Along the way, he attempted to update the gt2k work and update it to work with the latest Unity versions.  There was bits and pieces in the scene we borrowed.

I guess we could consider it early exploration?

**Comment by cvan** [comment]
Thanks! https://github.com/mozilla/unity-webvr-export#credits
