### ISSUE TITLE
add release notes (changelog) for each release version

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#210]
for https://github.com/mozilla/unity-webvr-export/releases

<hr>

inspiration:

- https://github.com/mrdoob/three.js/releases

**Comment by cvan** [comment]
just added release notes for **`v1.0.2`**: https://github.com/mozilla/unity-webvr-export/releases/tag/v1.0.2

**Comment by caseyyee** [comment]
This is already available in the "release" tab in repo. Should be sufficient?  Re-open if you have other ideas in mind.
