### ISSUE TITLE
Mouse click events are not triggered

### ISSUE THREAD

**Issue by fire67** [mozilla/unity-webvr-export#216]
Just add a Canvas and a button inside the demo scene with default properties.
When not in VR mode (referring to the bottom right button) the hover event is well triggered but the click is not.

Everything works fine in the editor but not in the browser.
Unity 2017.2.0p3

**Comment by fire67** [comment]
@cvan Thank you for your answer.
Yes, I imported the project inside Unity 2017.2.0p3 and added a canvas with a button inside the scene provided in the package, which is indeed the scene you are refering to.
I am currently using Firefox 59.0.2 (64 bits)

**Comment by cvan** [comment]
@fire67: could you share a sample of your code?

are you using the _WebVR Player_ template or the _WebGL Player_ template?

are you using our `index.html`, `webvr.js`, etc. template files?

- https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebGLTemplates/WebVR/webvr.js
- https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebGLTemplates/WebVR/index.html#L62-L64

thanks for the response - and helping us diagnose your issue 👍

**Comment by fire67** [comment]
Thank you very much for the super fast answer @cvan !
After some testing and thanks to the comment from @cflorea1 it appears that this was caused by the div with the `#instruction` selector.
In the last version the `pointer-events: none;` property fixes the issue. It works well now. :)
Thank you !
