### ISSUE TITLE
Provide a WebVR device emulator

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#217]
It would be nice if we can provide a device emulator for the Unity editor emulating the behaviour of the template in the browser so development would be confined to Unity only,

**Comment by caseyyee** [comment]
@delapuente I think this commit fixes this issue? https://github.com/mozilla/unity-webvr-export/commit/205eb280ce17de0b876f4f640d9d8f1fde6a3e8c

**Comment by delapuente** [comment]
This is for emulating the events happening in the browser. For instance, suppose we want to simulate we are switching off or disconnecting one of the controllers. This will happen on the WebVR side and handled in the browser resulting in some messages being dispatched to the C# code. In this emulator, we'd simulate sending those messages.

**Comment by caseyyee** [comment]
Gotcha.  That makes sense.

**Comment by caseyyee** [comment]
Mostly works now with in-editor XR support.
Implemented as part of cross-platform support https://github.com/mozilla/unity-webvr-export/pull/306
