### ISSUE TITLE
Matrix Math issue.

### ISSUE THREAD

**Issue by LordSkittles** [mozilla/unity-webvr-export#218]
Hello,

I have been using your library for a project and I came across an issue with your matrix math when the rig is moved.

If the camera rig is moved at any point, or even it's parent is moved at any point, and then you switch to VR mode from normal, all of the cameras inherit the parents transform positions, throwing the whole math off.

After looking through the code and debugging I found the issue.

The issue is with the following lines of code in WebVRCamera.cs script:

Line 224 `SetTransformFromViewMatrix (cameraL.transform, clv * sitStand.inverse * transform.worldToLocalMatrix);`
 Here you take the transform of the left eye camera, and set it to the worldToLocalMatrix.

Line 262 `transform.localPosition = trs.GetColumn(3);`
Line 263 `transform.localRotation = Quaternion.LookRotation(trs.GetColumn(2), trs.GetColumn(1));`

Here you now modify the passed transforms local values by an already localized matrix, this causes the camera to basically copy the transform values of the parent, 

i.e. if the parents transform is POS(0, 0, 10) ROT(-45, 0, 0) the camera will copy these and end up with POS(0, 0, 10) ROT(-45, 0, 0).

Here is the fix...

Line 262 `transform.position = trs.GetColumn(3);`
Line 263 `transform.rotation = Quaternion.LookRotation(trs.GetColumn(2), trs.GetColumn(1));`

Simply changing it from localPosition and localRotation to position and rotation will fix this, allowing all matricies to stay correct with the heirachy.

Cheers,
James Mills

**Comment by LordSkittles** [comment]
#184 This is the solution for that bug.

**Comment by delapuente** [comment]
Transforming the local position is an intended behaviour but you're right there is a double conversion involved. But perhaps I'm missing something. Can you describe the problem in more details?

**Comment by LordSkittles** [comment]
It's simple, just make your VR rig a child object, move the parent, and switch from normal mode to VR mode and you'll see the issue :P
