### ISSUE TITLE
use Gamepad `axes` in `webvr.js`

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#227]
see https://github.com/mozilla/unity-webvr-export/blob/db3b69f/Assets/WebGLTemplates/WebVR/webvr.js#L191-L196

(relevant to @caseyyee's work done in PR #224: https://github.com/mozilla/unity-webvr-export/pull/224/files#diff-2d10a72d69e50b854dd9042d2c774b53)

**Comment by delapuente** [comment]
Can you elaborate on this? What do you mean by "axes"?

**Comment by caseyyee** [comment]
Right now, we only capture button presses rather than gamepad axis for analogue inputs.

Probably can use the same scheme as we do with the buttons for axis.

**Comment by caseyyee** [comment]
fixed with https://github.com/mozilla/unity-webvr-export/commit/cde23e381da316460aa93caab7985234e6a8a62c
