### ISSUE TITLE
Enable static flags on static objects in example scene

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#228]
see PR #147 and the discussion. hat tip to @Legorobotdude for the contribution and useful suggestions. let's keep this going and figure out how to make all the static objects correctly marked as `Static`.

**Comment by caseyyee** [comment]
Done with https://github.com/mozilla/unity-webvr-export/commit/f9fe4302aef63cd529007d022699741bc47759df#diff-87eb99a2d1e7b48246e4f7c07d3b7cf2
