### ISSUE TITLE
expose FPS counter to measure perf

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#230]
could be an on-screen UI or preferably an in-VR UI

**Comment by caseyyee** [comment]
code already exists to do this:
https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebVR/Scripts/WebVRManager.cs#L199-L216

We removed the hotkey to enable/disable it.

**Comment by caseyyee** [comment]
Added basic performance HUD on `PostRender` events from Unity.

Displays when pressing `f` key in the browser.

https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebGLTemplates/WebVR/webvr.js#L133
