### ISSUE TITLE
Regressions on telemetry

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#234]
Converting `doNotTrack` into an only-once function (#225) introduces a regression consisting on [not honouring do-not-track feature](https://github.com/mozilla/unity-webvr-export/pull/225#pullrequestreview-111568127) if this is turned on in the middle of a session.

**Comment by cvan** [comment]
thanks for filing. I've reverted the PR #225 in PR #235 + followed up with PR #236
