### ISSUE TITLE
Error /webvr.js in onRequestPresent: `VR display is not capable of presenting`

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#237]
https://sentry.io/share/issue/a28dceb77c264712ae6f01290715d278/

- **Error**
- Chrome 64.0.3282
- Windows 10

![image](https://user-images.githubusercontent.com/203725/38703213-7489d9ee-3e57-11e8-88ac-542fbe34c589.png)

![image](https://user-images.githubusercontent.com/203725/38703233-83a35fb8-3e57-11e8-8974-5e61433d3a90.png)

**Comment by delapuente** [comment]
Can we reproduce this? Do we have more context?

**Comment by caseyyee** [comment]
File if we can replicate the issue.  There have been a lot of updates since, so hopefully this has been solved along the way?
