### ISSUE TITLE
update Unity Editor version (and document in README + docs)

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#250]
https://github.com/mozilla/unity-webvr-export/blob/master/ProjectSettings/ProjectVersion.txt

**Comment by caseyyee** [comment]
As per our slack convo.  I think we should think about freezing the editor version.  It must be a bit of a challenge keeping updated for anyone working on their projects whenever new versions of Unity come out.  Will need to look into what the best practice is here.

**Comment by cvan** [comment]
an possible idea that crossed my mind: what's your thoughts on this process:

`sendMessage` the Editor version from Unity -> JS -> Telemetry?

**Comment by caseyyee** [comment]
Might be available through gameInstance?  

Also looking at the log:
![image](https://user-images.githubusercontent.com/1560884/39032027-8b422136-4420-11e8-9068-91ce572d8cca.png)

Note line with `Initialize Engine Version`

**Comment by caseyyee** [comment]
Will update Unity editor on `f` (final) versions of Unity editor that have tangible benefit (either performance or dev ergonomics).  Best practice is to avoid upgrading when unnecessary to keep it easier for users of the Assets.
