### ISSUE TITLE
Add another demo scene (built using Unity)

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#268]
Arctic themed, so we can build URL to scene route.

**Comment by delapuente** [comment]
Is this a dup of #271 ?

**Comment by caseyyee** [comment]
That one looks to be a demo A-Frame scene that we can use to demonstrate links within the examples.

**Comment by cvan** [comment]
completed per https://github.com/mozilla/unity-webvr-export/issues/268#issuecomment-394901436
