### ISSUE TITLE
Asset package included scene should be complete

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#269]
We include the desert scene, but all the assets as part of the scene are not.   Should probably pull them together so it functions.

**Comment by delapuente** [comment]
I read some people offers a slim package with just the utilities and leave the scene and other demos in the repository, provide them as separate zip files or generate a custom package (like the one we have in the repo).

**Comment by caseyyee** [comment]
Gotcha.  Good to know.  If you have links, that would be useful.

**Comment by caseyyee** [comment]
Will leave scene in repo. 

Also added a section in the Getting Started docs that details starting from the project in this repo in addition of starting from a new 3D project:

https://github.com/mozilla/unity-webvr-export/pull/319
