### ISSUE TITLE
Detect WebVR in Chrome properly (2D instructions shown when WebVR is in fact available)

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#270]
Note the VR status + 2D instructions.

![image](https://user-images.githubusercontent.com/1560884/39713943-626cfb4e-51dd-11e8-84b8-39341f1b5e0d.png)

**Comment by cvan** [comment]
this was handled in PR #273, snuck it in to [`v1.3.0`](https://github.com/mozilla/unity-webvr-export/releases/tag/v1.3.0), which is already pushed to the [Unity Asset Store](https://assetstore.unity.com/packages/templates/systems/webvr-assets-109152).
