### ISSUE TITLE
hide "Toggle VR" UI on mobile/standalone (when `<VRDisplay>.capabilities.hasExternalDisplay === false`)

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#274]
it'd be nice if (for mobile/standalone WebVR), we hide the UI when `vrDisplay.capabilities.hasExternalDisplay === false`

**Comment by caseyyee** [comment]
fixed with https://github.com/mozilla/unity-webvr-export/commit/d121593fe721a7d3ef52e51c1cc364ea54a172d2#diff-2d10a72d69e50b854dd9042d2c774b53R160
