### ISSUE TITLE
simplify rendering order (i.e., `submitNextFrame`, etc.) and wrong rAF used in Chromium after subsequent VR sessions

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#275]
it's not entirely correct (and the tracking is hugely regressed), but here's where I'm at so far: https://github.com/mozilla/unity-webvr-export/compare/master...cvan:fix-rendering-order

**Comment by caseyyee** [comment]
Fixed as part of https://github.com/mozilla/unity-webvr-export/commit/d121593fe721a7d3ef52e51c1cc364ea54a172d2
