### ISSUE TITLE
Viewpoint is underground when using Oculus XR Settings

### ISSUE THREAD

**Issue by omgitsraven** [mozilla/unity-webvr-export#284]
When I test the default Unity WebVR scene in the Unity editor, my viewpoint is fine if I have OpenVR first in the XR Settings, but if I move Oculus to be first, then my head is way underground.

I'm using Unity 2018.1.0f2 and Oculus App Version 1.26.0.582280

**Comment by caseyyee** [comment]
Fixed with https://github.com/mozilla/unity-webvr-export/pull/316
