### ISSUE TITLE
Failing to detect screen centre in VR mode

### ISSUE THREAD

**Issue by kingbaggot** [mozilla/unity-webvr-export#291]
Hi - I can't seem to detect screen centre when in VR mode. Usually it's like this in Unity.

Vector2 screenCentre = new Vector2(XRSettings.eyeTextureWidth / 2, XRSettings.eyeTextureHeight / 2);

#if UNITY_EDITOR
  screenCentre = new Vector2(Screen.width / 2, Screen.height / 2);
#endif

and that handles it - but not with the Moz Web VR - I've looked into the desert scene for clues but can't find a solution.

Also because when the app switches cameras between the main and the L&R cams, code like this no longer functions correctly ?

Ray ray1 = myCamera.GetComponent<Camera>().ScreenPointToRay(screenCentre);

So do I need to constantly be checking in my main class which Camera should be the active one ?

ok cheers,

**Comment by kingbaggot** [comment]
Right - I know I can't use XRSettings (as they're not used) so I've taken my "screenCentre =...." out of the #if UNITY_EDITOR area - so at least the Web build detects the center in non-vr mode.

I still have do decide which camera to raycast from though. Any clues appreciate :)

**Comment by cvan** [comment]
cc @caseyyee

**Comment by caseyyee** [comment]
It would be helpful to know what exactly you are trying to do here, but screen center isn't really a thing for VR.  We have two separate viewports, one for each eye.  We can find screen center for the individual cameras, but i'm not sure how that would be useful (again, depends on your use here).  In 2D mode, screen center can be found using the code you have with `CameraMain`.

Hopefully that helps!
