### ISSUE TITLE
cannot get hand pose in oculus go controller

### ISSUE THREAD

**Issue by legokichi** [mozilla/unity-webvr-export#294]
Triggers button and touchpad work.
I think gamepad api has some problems.

**Comment by cvan** [comment]
thanks for filing. this will be handled in issue #288. after I wrap up a few unrelated bugs and enhancements, Oculus Go support (with proper handling of the controller) is the first task I'll be working on. if it's okay with you, I'll close this issue. feel free to comment in issue #288. again, thank you for reporting this. it's much appreciated! Oculus Go support coming soon! 👍
