### ISSUE TITLE
starting camera position is different in Unity XR player vs. WebVR export

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#303]
see this comment I made in @caseyyee's PR #295: https://github.com/mozilla/unity-webvr-export/pull/295#discussion_r194188654

> something in here caused the default camera position to be different (compare it to the position in `master`)
> ### with eb01ad3 (previously `master`)
> ![screenshot on `eb01ad3`, before entering VR](https://user-images.githubusercontent.com/203725/41182408-4cdf186e-6b2a-11e8-95f9-1ca6e719af8d.png)
> ![screenshot on `eb01ad3`, after entering VR](https://user-images.githubusercontent.com/203725/41182405-4c93f104-6b2a-11e8-8d2a-dd81ef51f1cd.png)

> ### in this branch
> ![screenshot after PR #295, before entering VR](https://user-images.githubusercontent.com/203725/41182406-4cad9910-6b2a-11e8-9517-5db6700970ab.png)
> ![screenshot after PR #295, after entering VR](https://user-images.githubusercontent.com/203725/41182407-4cc90786-6b2a-11e8-926e-33f55e3c7f96.png)

related issues:
- #284 for XR player for _Oculus_
- #102 for WebVR export for _Windows Mixed Reality_
- #154 for general improvements to the camera, specifically, per @delapuente:

    > During design time, there should be only one camera in the scene hierarchy. The camera is doubled in gameplay.

    > Most of the items were implemented in #159 . Changing the camera rigging to a unique camera duplicated in runtime feels like a considerable change in the way the prefab is used. Furthermore, [SteamVR Plugin](https://assetstore.unity.com/packages/templates/systems/steamvr-plugin-32647) also supports a stereo + mono camera rigging. I think this needs further discussion.

**Comment by caseyyee** [comment]
Seems to work for me now.  Reopen if you encounter this issue again!
