### ISSUE TITLE
does not render in Chrome Canary (with flags enabled)

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#307]
1. enable these flags in `chrome://flags`: _WebVR_, _Gamepad Extensions_, and _Oculus Hardware Support_/_OpenVR Hardware Support_
2. load `master` or the [demo scene](https://mozilla.github.io/unity-webvr-export/Build/)
3. notice that the scene does not properly enter VR mode

**Comment by caseyyee** [comment]
This seems to be working for me. Reopen if you continue to see an issue! Thanks.
