### ISSUE TITLE
Black Screen on Google Cardboard

### ISSUE THREAD

**Issue by VRRollerCoaster** [mozilla/unity-webvr-export#311]
I've ported two VR experiences to WebGL using this plugin and am having issues running them on both Google Cardboard & Google Daydream on the Google Pixel phone. 

1. Opening the webpage without VR is just fine:
![vrrollercoaster.app](http://pasteupload.com/images/2018/06/29/Screenshot_20180629-192530.png)
2. The problem is, when it runs, **after the instruction screen in full screen it goes black and doesn't come out of it**
![vrrollercoaster.app](http://pasteupload.com/images/2018/06/29/Screenshot_20180629-192542.png)
![vrrollercoaster.app](http://pasteupload.com/images/2018/06/29/Screenshot_20180629-192551.png)
3. When I hit the back button, it runs in windowed mode, but it's not ideal, with buttons blocking the view.
![vrrollercoaster.app](http://pasteupload.com/images/2018/06/29/Screenshot_20180629-192556.png)

The link to where you can see it is [vrrollercoaster.app](https://vrrollercoaster.app)

Thanks!

**Comment by caseyyee** [comment]
As per @cvan in slack, this is probably due to the polyfill issue:
https://github.com/mozilla/unity-webvr-export/issues/253

**Comment by VRRollerCoaster** [comment]
Thanks @caseyyee I see it has already been brought up. Is there a fix for this in newer commits yet? I'm using v1.3.0 and haven't tried newer commits yet.

**Comment by caseyyee** [comment]
I haven't had a chance to look at this yet, but I will early next week!  Thanks.

**Comment by caseyyee** [comment]
Testing this issue:

![image](https://user-images.githubusercontent.com/1560884/42475061-5bbf7ee8-837e-11e8-9b07-471d20f0b84b.png)

The experience seems to load for me, but when I hit _Enter VR_, I get a canvas error.

![chrome_2018-07-09_13-37-07](https://user-images.githubusercontent.com/1560884/42474946-f68596ca-837d-11e8-82c6-546957feec8d.png)

**Comment by VRRollerCoaster** [comment]
Hi,
I updated to the new release, (and while Web VR Roller Coaster is still running choppy and slow), this specific issue of the black screen seems to be gone.

**Comment by caseyyee** [comment]
@VRRollerCoaster what hardware are you using?

**Comment by VRRollerCoaster** [comment]
Pixel XL (1st generation)

**Comment by caseyyee** [comment]
@VRRollerCoaster have you tried the latest 1.4 updates to see if that helps the issue?  You should only get the exit VR bug at this moment.  I do notice that it black-screens for a few moments until the player wakes up.

**Comment by vingkan** [comment]
Also experiencing this problem. I cloned this repo and hosted it on [GitHub pages](https://vingkan.github.io/unity-webvr-export/Build/) without making any changes and encountered the black screen error when trying to full screen on Nexus 6P.

Then, I tried to use the v1.4 release, did not change the results.

[Repository Link](https://github.com/vingkan/unity-webvr-export)

CC: @lihnick who is teaching a VR class and unable to successfully export the student's games because of this issue.

**Comment by caseyyee** [comment]
This seems to work now as of https://github.com/mozilla/unity-webvr-export/pull/328

**Comment by aj17** [comment]
Hi, 
With reference to this issue . I checked with current update of the code.
Built the given example , has same error as mine.
I have OnePlus 5.
Screen Shot is of the Developer Tool.
![image](https://user-images.githubusercontent.com/12268056/45617713-cd773a00-ba90-11e8-98d0-b25b83ddbbf1.png)

**Comment by caseyyee** [comment]
@aj17 The issue reported here was for daydream, so could be a separate issue.  I'll check with a phone that does not have VR support and see if I get the same issue.  Are you using the version downloaded from this repo or the asset store?
