### ISSUE TITLE
Include unity InputManager.asset button/axis mappings in package.

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#312]
Not sure how this is usually done when distributing assets, but we'll need this to avoid users from having to configure inputs manually.

**Comment by caseyyee** [comment]
It's already included, but it would be nice to not have to copy this into your own project.  I think we could probably have a editor script automatically load inputs into the InputManager for you in some kind of install step ([like rewire does](http://guavaman.com/projects/rewired/docs/Installation.html))

some possible options:
http://plyoung.appspot.com/blog/manipulating-input-manager-in-script.html

**Comment by StephenHodgson** [comment]
So you're saying we should use rewired instead?

**Comment by caseyyee** [comment]
@StephenHodgson Would be nice.  Know of a open source alternative? It would be nice to be able to bypass the Unity Input system, but that doesn't seem possible at the moment. Hopefully the new Input system will give us some options, but for now, it seems like it's still in development.

**Comment by StephenHodgson** [comment]
You could always get input from the native plugins.  That's what we're considering for the Mixed Reality toolkit Input system.

**Comment by caseyyee** [comment]
I don't think that's an option since the Input is mediated through the browser using Gamepad API.  There doesn't appear to be a good way to `Input.GetAxis` without using the Unity Input manager, so for now we will ask users to copy `InputManager.asset` into their own project until we find a better solution.

**Comment by caseyyee** [comment]
Fixed with https://github.com/mozilla/unity-webvr-export/commit/1853dbf2a581eb4c29fab79e518529399905d70a

Will come back to a better solution for this one at a later date.
