### ISSUE TITLE
"WebVRCameraSet not found" for test scene

### ISSUE THREAD

**Issue by omgitsraven** [mozilla/unity-webvr-export#322]
I just updated to Unity 2018.2.0f2 and WebVR Assets 1.4.0.

1. I created a new project in Unity Hub, that included WebVR Assets.
2. The project loaded.
3. There were immediately 999+ errors in the console, even after clicking 'clear'. (They were all related to .js files inside of `Assets/WebGLTemplates/WebVR`)
4. I quit and relaunched Unity. The errors were all gone. (That much isn't new, it's always been that way for me, I just thought I should mention it.)
5. I opened WebVR/Scenes/WebVR
6. I turned off "baked global illumination", because the bake was going to take over an hour.
7. I did 'build settings', switched it to WebGL, and hit Build And Run (and created a folder).
8. It launched in Firefox (61.0.1) (which normally runs WebVR content fine)
9. I hit the VR button, and the console printed `SendMessage: object WebVRCameraSet not found!`, and my headset just showed a static view that made me feel crosseyed (I think the desktop image was just stretched across both eyes)

I've tried this entire setup three times now and it's the same result every time.
Everything worked fine when I tried it a few months ago.

**Comment by jwatDev** [comment]
I'm experiencing the same issue, but can report a more recent test window. I had it functioning on 7/17, and it now reports the same bug. I'm on FF 60.1.0esr (32-bit).

**Comment by caseyyee** [comment]
I've run into this issue a bunch before.  It seems that its not anything with code, but Unity itself.  

Try removing the prefab, and re-adding it back to your scene.  I have also had some luck with re-creating game objects and and re-adding components.  Unsure what causes this. 

Thanks for the report!  I wasn't sure if this was specific to my setup.

**Comment by jwatDev** [comment]
The bug seems to start basically anytime I make any edits to the prefab.  I've extracted my changes and tried adding them back more delicately but it seems to cause the same result. I'm not removing anything from the prefab, just adding to it and editing colliders.

**Comment by caseyyee** [comment]
I've updated the editor version and it seems to have solved this issue. I haven't encountered it since.
Reopen if you see otherwise!

**Comment by kanonji** [comment]
I have encountered the same issue on Unity 2018.2.7f1 and WebVR Assets 1.4.0.
As I find this page, I have tried upgrading Unity to  2018.2.8f1 and importing WebVR Assets 1.5.0, but I am still in trouble of the issue.

Here this is my build.
http://totebox.kanonji.info/2018-09-16-mozilla-webvr-for-github-issue/


I got WebVR Assets 1.5.0 from GitHub because the Asset store is providing 1.4.0.
Downloading https://github.com/mozilla/unity-webvr-export/archive/1.5.0.zip and extract WebVR-Assets.unitypackage from the zip.

@caseyyee I can not reopen this, so should I make a new issue for my case?

**Comment by kanonji** [comment]
![sunny desert _ try-unity-asset-webvr-assets-109152 - google chrome 2018-09-17 04 55 30](https://user-images.githubusercontent.com/134377/45600329-f3bbbc00-ba35-11e8-9117-ea08b445ce9f.png)

I put `Debug.Log()` on end of `Awake()` and `Start()` of WebVRManager.cs to inspect.
As shown in the picture above, javascript seems to try `SendMessage` before WebVRManager started.
I guess must wait WebVRManager started before `SendMessage`.

**Comment by kanonji** [comment]
After additional inspection, I find the timing of `SendMessage ` detailed above is not related to the bug.
So forget about that.
I am going to inspect other more.

**Comment by caseyyee** [comment]
@kanonji I'm really sorry bout that.  I should make it clearer that the latest versions here on github are not necessarily the ones pushed up to the asset store.  New one will be pushed up soon though!
