### ISSUE TITLE
HELP! I can't open WebVR by OculusGo

### ISSUE THREAD

**Issue by akio-okumura** [mozilla/unity-webvr-export#325]
Nice to meet you, my name is Akio Okumura of Japan who began developing WebVR.
I attempted to implement VR with Unity's WebGL using Mozilla's WebVRAsset, but I am not going well.
Specifically, I did it according to this YouTube.
https://www.youtube.com/watch?time_continue=17&v=ipLwVV31lEo
I placed the output file in GitHubPages and opened it with OculusGo browser.
And I did VR mode, but tracking of OculusGo has not been done and I can not look around.
Please tell me if there is a solution.

https://github.com/akio-okumura/WebGLUpload/tree/gh-pages

**Comment by caseyyee** [comment]
@akio-okumura This should be working now with the latest updates in the repo.  Let me know if you are still encountering issues!
