### ISSUE TITLE
I immediately get compiler errors

### ISSUE THREAD

**Issue by arendr** [mozilla/unity-webvr-export#327]
I followed the instructions to add the WebVRCameraSet and inputmanager.assets files, but when I preview I just get lots of compiler errors. This is with a blank project, and I've removed my Main Camera. 

I'm on Unity 2018.2.5f1.

EDIT: I restarted Unity and it now appears to work.

**Comment by caseyyee** [comment]
@arendr I just updated the project to 2017.2.6f1.  Should be good to go!
