### ISSUE TITLE
How to make Unity project support WebXR?

### ISSUE THREAD

**Issue by geniusywj** [mozilla/unity-webvr-export#333]
When WebXR is enabled and WebVR is disabled, we cannot run the unity project on Chrome. How to support WebXR then?

**Comment by caseyyee** [comment]
Thanks for filing the issue!  We have one open already for WebXR support:
https://github.com/mozilla/unity-webvr-export/issues/85

Is there something else not covered by that issue that you see?  Otherwise, I think closing this one in favor of #85 would make sense.
