### ISSUE TITLE
No Immersion using Chrome

### ISSUE THREAD

**Issue by ciib** [mozilla/unity-webvr-export#336]
We tried to implement a scene with webvr and unity. But if we loaded the scene from the server on different android devices the camera was shown in stereo but the movement was not working. Although the stereo of the camera was not overlapping.

We found that in the [WebVRManager-Script](https://github.com/mozilla/unity-webvr-export/blob/master/Assets/WebVR/Scripts/WebVRManager.cs) on **line 66** is a change of the WebVRCameraSet Gameobject name. But the original name (WebVRCameraSet) is necessary to generate the immersion. If I delete this line, it works fine for us. 

I just want to send you this bugfix by us to solve this issue. It would be better to use tags instead of names for find gameobjects in a scene?

**Comment by caseyyee** [comment]
Thank @Banyango for the fix!
