### ISSUE TITLE
JS `Screen position out of view frustum` errors in Chrome Canary

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#64]
0. ensure you are on Windows and have Steam VR installed (tested on Dell Visor MR and Vive headsets)
1. download **[Chrome Canary](https://www.google.com/chrome/browser/canary.html)** for Windows
1. ensure these Chrome flags are all marked as **`Enabled`**:
    - WebVR — `chrome://flags#enable-webvr`
    - OpenVR — `chrome://flags#openvr`
    - Gamepad Extensions — `chrome://flags#enable-gamepad-extensions`
1. load https://caseyyee.github.io/unity-webvr-export/Build/
1. after "Loading..." screen, the **scene is black**. until I press the "Enter VR" button, there are constant **Console errors**: `Screen position out of view frustum    blob:https://caseyye…c-66cfdf698c02:7636 `
1. when I click the "Enter VR" button, the errors stop and the stereo, mirrored canvas appears as expected. when I toggle from mono to stereo, after that, it's fine.

**Comment by cvan** [comment]
The above errors I first reproduced with a Dell Visor (Windows Mixed Reality) headset. I was able to reproduce this issue on the Vive on Windows. Here are some screenshots:

![image](https://user-images.githubusercontent.com/203725/35178050-fb17e60e-fd39-11e7-847e-b4bb2f105d97.png)
![image](https://user-images.githubusercontent.com/203725/35178055-0d39d0f4-fd3a-11e7-8e46-8dca23e48377.png)
![image](https://user-images.githubusercontent.com/203725/35178058-1014bf14-fd3a-11e7-93b2-7ae69291f923.png)
![image](https://user-images.githubusercontent.com/203725/35178060-141762b0-fd3a-11e7-93a6-00ad4aec85cd.png)
![image](https://user-images.githubusercontent.com/203725/35178064-1963487e-fd3a-11e7-928f-4119bf8dcc63.png)

**Comment by delapuente** [comment]
FYI, I got this error in Unity when the camera is very far from the origin.

**Comment by caseyyee** [comment]
oh interesting.   do you mean far away from 0,0,0 world origin?  moving the cameraset prefab?  eg 1000, 0, 0 or something like that?  I'll give it a try.  thanks!

**Comment by delapuente** [comment]
I mean super far away from the origin. Not like 1000 but much more.

**Comment by cvan** [comment]
so, y'all still see this error? what about in PR #132?

I can't reproduce it anymore. I'll try with my other VR setups, one which has a much larger play space (stage).

**Comment by delapuente** [comment]
I'm pretty confident in #132 solving this issue too.
