### ISSUE TITLE
move repo to mozilla

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#67]

**Comment by caseyyee** [comment]
Oh, just thinking here.  We will want some place to put example projects built using these components as well.   Is it better to have a separate org for this?

**Comment by cvan** [comment]
Do we have a product name for this?

This is probably a good time to consider making this a `monorepo`.

**Comment by larsbergstrom** [comment]
@edunham I think we're trying to move this to the `mozvr` GH org for now, and will plan to rename that GH org in the future but are blocked on some GitHub issue w/ the moving?

**Comment by cvan** [comment]
I know @edunham and @caseyyee were working on move this to the `mozilla` org (which it is now). but, yeah, @larsbergstrom, I thought we wanted to consolidate all of our projects to the `mozvr` org?

this can be discussed in a separate thread, but @larsbergstrom, if you want me to change the `mozvr` org to `MozillaResearch`, I can do that now. the redirects and everything will just work.

**Comment by caseyyee** [comment]
done!

**Comment by cvan** [comment]
@caseyyee: see my comment above https://github.com/mozilla/unity-webvr-export/issues/67#issuecomment-363245330
