### ISSUE TITLE
The demo project should require zero setup

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#77]
Unless it is a tutorial, the demo project should not require additional setup. Simply run and everything should be working.

**Comment by caseyyee** [comment]
I don't understand this issue.  The project is pretty much works out of the box as it is now?  @delapuente, can you give us more specifics?

**Comment by delapuente** [comment]
At the time I open this issue, it required some setup. Now the issue is invalid. Closing.
