### ISSUE TITLE
The default WebVR scene should showcase basic interactions

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#78]
The demo should show typical game grab interactions.

**Comment by caseyyee** [comment]
This was originally filed as issue https://github.com/mozilla/unity-webvr-export/issues/78.   As per the issue, we want to have available components for basic interactions and have them available within the basic WebVR scene.  Not necessarily a demo/game.

**Comment by cvan** [comment]
Relevant enhancement: `Provide components to make objects to be controlled by VR controllers` **issue #162**

**Comment by caseyyee** [comment]
Moved teleport into its own issue https://github.com/mozilla/unity-webvr-export/issues/203

**Comment by caseyyee** [comment]
Fixed with https://github.com/mozilla/unity-webvr-export/commit/b0a1307d5f722f066f3a0f5c69ae4c889fee9457
