### ISSUE TITLE
Page load blocked on JS error `TypeError: vrDisplay is null` (thrown intermittently); causes Gecko to crash!

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#99]
when opening in Firefox using windows MR.  Seems to happen when headset is idle on not on my head.

Not exactly sure where it is originating from.  Polyfill maybe?

**Comment by cvan** [comment]
This smells like a Firefox platform bug. If so, I can file a Bugzilla Gecko bug. Perhaps this could be solved in the meantime with a hack of adding an event listener for `vrdisplayconnect`: `window.addEventListener('vrdisplayconnect', function () { getVRDisplays(); });`

somewhat related: [looks like the `vrdisplayconnect` event](https://github.com/immersive-web/webvr-polyfill/issues/303#issuecomment-362406395
) still fires every time upon page load if there's a VR display connected

also, could you paste a screenshot and/or JS Console errors/warnings?

**Comment by cvan** [comment]
@caseyyee: do you think this belongs in the initial milestone?

**Comment by caseyyee** [comment]
![unity-webvr-export - firefox nightly 2018-02-06 11_39_55 pm](https://user-images.githubusercontent.com/1560884/35904242-43074f0c-0b97-11e8-8fa2-22518727ab1c.png)

**Comment by caseyyee** [comment]
@cvan I don't think we need to block on this.  I think it only happens in Nightly.

**Comment by caseyyee** [comment]
Actually, I think this might be  C# code in Unity.   Some types of errors are raised as alert boxes for some reason.  I'll dig in.

@cvan its intermittent.   I'll see if I can resolve, but I don't think we need to block.

**Comment by cvan** [comment]
@caseyyee:

if you log each event in `onUnity`, what's the order of the events? I assume `"Ready"` is always getting fired first, yes?

try adding this to `index.html`:

```js
          onProgress: unityProgress,
          handler: errorhandler
        });

        var errorhandler = function (msg, url, lineNo, columnNo, error) {
            console.error('Message: %s; URL: %s; Line: %s, Column: %s; Error:\n',
              msg,
              url,
              lineNo,
              columnNo,
              error);
          return false;
        });
```

**Comment by cvan** [comment]
from @kearwood:

> call GetVRDisplays on load if you detect Firefox 58 and see if a VRDisplay is returned. Waiting for vrdisplayconnect before using GetVRDisplays is best in all other cases and in FF59+; however.

@caseyyee: can you try that?

**Comment by cvan** [comment]
having the headset on or off doesn't seem to affect this. I can't figure out reliable steps to reproduce this. @caseyyee: if you can, let me know.

**Comment by cvan** [comment]
additional follow up: I rebuilt the Unity project, and I encountered the issue immediately. and after I dismissed the `alert` prompt, Firefox Nightly crashed.

here's one of the crashes: https://crash-stats.mozilla.com/report/index/8b59877c-48ec-4d69-a5f4-9e2da0180208

![image](https://user-images.githubusercontent.com/203725/35956827-dbe0a7e0-0c4c-11e8-8483-d3ba38a69981.png)

looks like the crash happened at `nsGlobalWindowInner::DispatchVRDisplayActivate(unsigned int, mozilla::dom::VRDisplayEventReason)`

@kearwood: any ideas? (@caseyyee: looks like, regardless of the fix/workaround we discover, we ought to file a Gecko platform bug on Bugzilla for this.)

**Comment by delapuente** [comment]
It is worth solving or researching this issue bat not blocking on it so, moving to the next release.

**Comment by delapuente** [comment]
Can we retest this *after* merging #132 It is probable that PR can solve this too. But this is something we should address properly, talking to Unity folks to determine the exact order of the events.

**Comment by cvan** [comment]
also, I'll set a task item for me to file a Bugzilla bug. no matter how poorly I write my WebVR event listeners, I shouldn't be able to crash Gecko 💥!

**Comment by caseyyee** [comment]
works for me.  reopen if you encounter this issue!
